import json
from utils.get_llm_response_generator import create_code_generator
from utils.generation_functions.generate_prompt import generate_code_with_openai
from pathlib import Path

def save_dict_to_json(data: dict, file_path: str | Path, *, indent: int = 4) -> None:
    """
    Serialize a Python dictionary to a JSON file, creating any
    intermediate directories that don’t yet exist.

    Parameters
    ----------
    data : dict
        The dictionary you want to save.
    file_path : str | Path
        Destination path (e.g. "output/settings/config.json").
    indent : int, optional
        Pretty-print spacing in the resulting file (default = 4).
    """
    file_path = Path(file_path)                 # allow strings or Path objects

    # Ensure parent directories exist (no error if they’re already there)
    file_path.parent.mkdir(parents=True, exist_ok=True)

    # Write the JSON file with UTF-8 encoding
    with file_path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=indent, ensure_ascii=False)

graph_definitions = {
    "Sparse_Graph": (
        "A graph is considered sparse when the number of edges |E| is much smaller "
        "than the maximum possible number of edges. |E| << |V |(|V| - 1) / 2 (unndirected); |E| << |V |(|V|- 1) / 2 (directed graph)"
    ),
    "Planar_Graph": (
        "A graph that can be drawn in the plane without any edge intersections "
        "(except at shared vertices); for a finite, connected planar graph, "
        "Euler's formula |V| - |E| + |F| = 2 ."
    ),
    "Regular_Graph": (
        "A graph is k-regular if every vertex has the same degree k."
    ),
    "Dense_Graph": (
        "A graph whose edge density D is high (e.g., D = 0.7), where "
        "for undirected graphs D = 2|E| / |V|(|V| - 1) and for directed graphs "
        "D = |E| / |V|(|V| - 1)."
    ),
    "Complete_Graph": (
        "A graph in which an edge exists between every pair of distinct vertices."
    ),
    "Small_World_Graph": (
        "A graph generated by the Watts-Strogatz model, characterized by short "
        "average path lengths and high clustering; defined by parameters "
        "n (nodes), k (nearest neighbors), and p (rewiring probability)."
    ),
    "Erdos_Renyi_Graph": (
        "A random graph following the G(n, p) model in which each possible edge "
        "appears independently with probability p."
    ),
    "Power_Law_Graph": (
        "A scale-free network produced by preferential attachment in the "
        "Barabasi-Albert model, whose degree distribution follows a power law "
        # "P(k) ∝ k^{-γ}."
    )
}

print("Initialising code generate agent")
openai_model_code_generate = create_code_generator(
    model_name="deepseek-reasoner",
    system_prompt="You are an expert in graph theory and graph-related tasks"
    )
print("DeepSeek Code Generation Agent Initialised")

example_description_path = f"../evaluation_dataset/GWild_docs/function_pages/task_examples.json"
with open(example_description_path, "r", encoding="utf-8") as f:
    task_nx_examples = json.load(f)
task_path = f"/data/chenglin/GraphTutor/Dataset/training_dataset/gwild_filtered.json"
with open(task_path, "r", encoding="utf-8") as f:
    tasks = json.load(f)
task_name_graph_type_dict = {}
for task_nx_example in task_nx_examples:
    task_name = task_nx_example["function"]
    question = tasks[task_name][0]["input"]
    graph_def = json.dumps(graph_definitions)
    # import pdb;pdb.set_trace()
    user_query = (
        f"Based on the input graph task {task_name}",
        f"Carefully look at the graph categories and explanation in this dictionary: {graph_def}",
        f"Here is a sample question for the given graph task {question}",
        f"Select the graph categories that can be used in the input graph task from this given dictionary. And return the selected graph categories in a list"
        f"Return your answer without any explanation, "
        )
    result = generate_code_with_openai(
    query=json.dumps(user_query), 
    openai_model=openai_model_code_generate, 
    retrieved_docs=None,
    instrcution="You are a sophisticated AI expert in graph theory and algorithms.")
    task_name_graph_type_dict[task_name] = result
    save_dict_to_json(task_name_graph_type_dict, f"../evaluation_dataset/GWild_docs/graph_types_for_task/types.json")

    
    
    